backend:
  name: github
  repo: peiiii/peiiii.github.io
  branch: master # Branch to update (optional; defaults to master)
  api_root: https://api.github.com
publish_mode: editorial_workflow
media_folder: "static/img/uploads" # Media files will be stored in the repo under images/uploads
public_folder: "/img/uploads" # The src attribute for uploaded media will begin with /images/uploads
